question_data = [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "Coca-Cola&#039;s original colour was green.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "The vapor produced by e-cigarettes is actually water.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "Furby was released in 1998.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "The commercial UK channel ITV stands for &quot;International Television&quot;.", "correct_answer": "False", "incorrect_answers": ["True"]}
    ]
